[package]
name = "horsie"
version = "0.0.1"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
bitvec = "1.0.1"
rand = "0.9.2"
rand_xorshift = "0.4.0"

[profile.opt-debug]
inherits = "release"
debug = true
